-- Sections géographie : « Devine le drapeau » et « Capitales ».
-- Migration purement additive : aucune table existante n'est modifiée.
-- Les cartes réutilisent le même état mémoire FSRS que les flashcards
-- (backend/src/srs.rs), sans dépendre d'une matière : la géographie est
-- transversale, elle vit hors de l'arborescence subjects/blocks.

CREATE TYPE geo_kind AS ENUM ('flag', 'capital');

-- Référentiel des pays, seedé par cette migration (jeu de données figé :
-- 197 États = 193 membres de l'ONU + Vatican, Palestine, Taïwan, Kosovo).
CREATE TABLE geo_countries (
    iso2             CHAR(2) PRIMARY KEY,          -- sert aussi à dériver le drapeau (indicateurs régionaux)
    name_fr          TEXT NOT NULL,
    name_accepted    TEXT[] NOT NULL,              -- toutes les réponses admises pour le nom (name_fr inclus)
    capital_fr       TEXT NOT NULL,
    capital_accepted TEXT[] NOT NULL,              -- co-capitales et variantes d'usage incluses
    continent        TEXT NOT NULL
);
CREATE INDEX idx_geo_countries_continent ON geo_countries(continent);

-- Une carte par (mode, pays) : état mémoire FSRS identique à flashcards.
CREATE TABLE geo_cards (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind          geo_kind NOT NULL,
    iso2          CHAR(2) NOT NULL REFERENCES geo_countries(iso2) ON DELETE CASCADE,

    -- ---- FSRS memory state (meme forme que flashcards) ----
    stability     REAL,
    difficulty    REAL,
    state         card_state NOT NULL DEFAULT 'new',
    due           TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_reviewed TIMESTAMPTZ,
    reps          INT NOT NULL DEFAULT 0,
    lapses        INT NOT NULL DEFAULT 0,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (kind, iso2)
);
CREATE INDEX idx_geo_cards_queue ON geo_cards(kind, due);
CREATE INDEX idx_geo_cards_iso2  ON geo_cards(iso2);

-- Journal append-only des réponses (miroir de reviews, avec la saisie brute
-- pour pouvoir auditer les quasi-réponses refusées par le moteur).
CREATE TABLE geo_answers (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    card_id          UUID NOT NULL REFERENCES geo_cards(id) ON DELETE CASCADE,
    session_id       UUID REFERENCES study_sessions(id) ON DELETE SET NULL,
    answered_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    given            TEXT NOT NULL,
    correct          BOOLEAN NOT NULL,
    rating           SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 4),
    elapsed_days     INT NOT NULL,
    stability_after  REAL,
    difficulty_after REAL,
    scheduled_days   INT NOT NULL
);
CREATE INDEX idx_geo_answers_card ON geo_answers(card_id, answered_at);

INSERT INTO geo_countries (iso2, name_fr, name_accepted, capital_fr, capital_accepted, continent) VALUES
    ('ZA', 'Afrique du Sud', '{"Afrique du Sud","République sud-africaine"}', 'Pretoria', '{"Pretoria","Le Cap","Cape Town","Bloemfontein"}', 'Afrique'),
    ('DZ', 'Algérie', '{"Algérie"}', 'Alger', '{"Alger"}', 'Afrique'),
    ('AO', 'Angola', '{"Angola"}', 'Luanda', '{"Luanda"}', 'Afrique'),
    ('BJ', 'Bénin', '{"Bénin"}', 'Porto-Novo', '{"Porto-Novo","Cotonou"}', 'Afrique'),
    ('BW', 'Botswana', '{"Botswana"}', 'Gaborone', '{"Gaborone"}', 'Afrique'),
    ('BF', 'Burkina Faso', '{"Burkina Faso","Burkina"}', 'Ouagadougou', '{"Ouagadougou"}', 'Afrique'),
    ('BI', 'Burundi', '{"Burundi"}', 'Gitega', '{"Gitega","Bujumbura"}', 'Afrique'),
    ('CM', 'Cameroun', '{"Cameroun"}', 'Yaoundé', '{"Yaoundé"}', 'Afrique'),
    ('CV', 'Cap-Vert', '{"Cap-Vert","Cabo Verde"}', 'Praia', '{"Praia"}', 'Afrique'),
    ('KM', 'Comores', '{"Comores","Union des Comores"}', 'Moroni', '{"Moroni"}', 'Afrique'),
    ('CI', 'Côte d''Ivoire', '{"Côte d''Ivoire"}', 'Yamoussoukro', '{"Yamoussoukro","Abidjan"}', 'Afrique'),
    ('DJ', 'Djibouti', '{"Djibouti"}', 'Djibouti', '{"Djibouti"}', 'Afrique'),
    ('EG', 'Égypte', '{"Égypte"}', 'Le Caire', '{"Le Caire","Caire"}', 'Afrique'),
    ('ER', 'Érythrée', '{"Érythrée"}', 'Asmara', '{"Asmara","Asmera"}', 'Afrique'),
    ('SZ', 'Eswatini', '{"Eswatini","Swaziland"}', 'Mbabane', '{"Mbabane","Lobamba"}', 'Afrique'),
    ('ET', 'Éthiopie', '{"Éthiopie"}', 'Addis-Abeba', '{"Addis-Abeba","Addis Ababa"}', 'Afrique'),
    ('GA', 'Gabon', '{"Gabon"}', 'Libreville', '{"Libreville"}', 'Afrique'),
    ('GM', 'Gambie', '{"Gambie"}', 'Banjul', '{"Banjul"}', 'Afrique'),
    ('GH', 'Ghana', '{"Ghana"}', 'Accra', '{"Accra"}', 'Afrique'),
    ('GN', 'Guinée', '{"Guinée","Guinée-Conakry"}', 'Conakry', '{"Conakry"}', 'Afrique'),
    ('GQ', 'Guinée équatoriale', '{"Guinée équatoriale"}', 'Malabo', '{"Malabo"}', 'Afrique'),
    ('GW', 'Guinée-Bissau', '{"Guinée-Bissau","Guinée-Bissao"}', 'Bissau', '{"Bissau","Bissao"}', 'Afrique'),
    ('KE', 'Kenya', '{"Kenya"}', 'Nairobi', '{"Nairobi"}', 'Afrique'),
    ('LS', 'Lesotho', '{"Lesotho"}', 'Maseru', '{"Maseru"}', 'Afrique'),
    ('LR', 'Liberia', '{"Liberia","Libéria"}', 'Monrovia', '{"Monrovia"}', 'Afrique'),
    ('LY', 'Libye', '{"Libye"}', 'Tripoli', '{"Tripoli"}', 'Afrique'),
    ('MG', 'Madagascar', '{"Madagascar"}', 'Antananarivo', '{"Antananarivo","Tananarive"}', 'Afrique'),
    ('MW', 'Malawi', '{"Malawi"}', 'Lilongwe', '{"Lilongwe"}', 'Afrique'),
    ('ML', 'Mali', '{"Mali"}', 'Bamako', '{"Bamako"}', 'Afrique'),
    ('MA', 'Maroc', '{"Maroc"}', 'Rabat', '{"Rabat"}', 'Afrique'),
    ('MU', 'Maurice', '{"Maurice","Île Maurice"}', 'Port-Louis', '{"Port-Louis"}', 'Afrique'),
    ('MR', 'Mauritanie', '{"Mauritanie"}', 'Nouakchott', '{"Nouakchott"}', 'Afrique'),
    ('MZ', 'Mozambique', '{"Mozambique"}', 'Maputo', '{"Maputo"}', 'Afrique'),
    ('NA', 'Namibie', '{"Namibie"}', 'Windhoek', '{"Windhoek"}', 'Afrique'),
    ('NE', 'Niger', '{"Niger"}', 'Niamey', '{"Niamey"}', 'Afrique'),
    ('NG', 'Nigeria', '{"Nigeria","Nigéria"}', 'Abuja', '{"Abuja"}', 'Afrique'),
    ('UG', 'Ouganda', '{"Ouganda"}', 'Kampala', '{"Kampala"}', 'Afrique'),
    ('CF', 'République centrafricaine', '{"République centrafricaine","Centrafrique","RCA"}', 'Bangui', '{"Bangui"}', 'Afrique'),
    ('CD', 'République démocratique du Congo', '{"République démocratique du Congo","RDC","RD Congo","Congo-Kinshasa","Zaïre"}', 'Kinshasa', '{"Kinshasa"}', 'Afrique'),
    ('CG', 'République du Congo', '{"République du Congo","Congo","Congo-Brazzaville"}', 'Brazzaville', '{"Brazzaville"}', 'Afrique'),
    ('RW', 'Rwanda', '{"Rwanda"}', 'Kigali', '{"Kigali"}', 'Afrique'),
    ('ST', 'São Tomé-et-Principe', '{"São Tomé-et-Principe","Sao Tomé-et-Principe","São Tomé-et-Príncipe"}', 'São Tomé', '{"São Tomé","Sao Tome"}', 'Afrique'),
    ('SN', 'Sénégal', '{"Sénégal"}', 'Dakar', '{"Dakar"}', 'Afrique'),
    ('SC', 'Seychelles', '{"Seychelles"}', 'Victoria', '{"Victoria"}', 'Afrique'),
    ('SL', 'Sierra Leone', '{"Sierra Leone"}', 'Freetown', '{"Freetown"}', 'Afrique'),
    ('SO', 'Somalie', '{"Somalie"}', 'Mogadiscio', '{"Mogadiscio","Mogadishu"}', 'Afrique'),
    ('SD', 'Soudan', '{"Soudan"}', 'Khartoum', '{"Khartoum"}', 'Afrique'),
    ('SS', 'Soudan du Sud', '{"Soudan du Sud","Sud-Soudan"}', 'Djouba', '{"Djouba","Juba"}', 'Afrique'),
    ('TZ', 'Tanzanie', '{"Tanzanie"}', 'Dodoma', '{"Dodoma","Dar es Salam","Dar es Salaam"}', 'Afrique'),
    ('TD', 'Tchad', '{"Tchad"}', 'N''Djamena', '{"N''Djamena","Ndjamena","N''Djaména"}', 'Afrique'),
    ('TG', 'Togo', '{"Togo"}', 'Lomé', '{"Lomé"}', 'Afrique'),
    ('TN', 'Tunisie', '{"Tunisie"}', 'Tunis', '{"Tunis"}', 'Afrique'),
    ('ZM', 'Zambie', '{"Zambie"}', 'Lusaka', '{"Lusaka"}', 'Afrique'),
    ('ZW', 'Zimbabwe', '{"Zimbabwe"}', 'Harare', '{"Harare"}', 'Afrique'),
    ('AG', 'Antigua-et-Barbuda', '{"Antigua-et-Barbuda"}', 'Saint John''s', '{"Saint John''s","Saint Johns","St John''s","Saint-John''s"}', 'Amériques'),
    ('AR', 'Argentine', '{"Argentine"}', 'Buenos Aires', '{"Buenos Aires"}', 'Amériques'),
    ('BS', 'Bahamas', '{"Bahamas"}', 'Nassau', '{"Nassau"}', 'Amériques'),
    ('BB', 'Barbade', '{"Barbade"}', 'Bridgetown', '{"Bridgetown"}', 'Amériques'),
    ('BZ', 'Belize', '{"Belize","Bélize"}', 'Belmopan', '{"Belmopan"}', 'Amériques'),
    ('BO', 'Bolivie', '{"Bolivie"}', 'Sucre', '{"Sucre","La Paz"}', 'Amériques'),
    ('BR', 'Brésil', '{"Brésil"}', 'Brasilia', '{"Brasilia","Brasília"}', 'Amériques'),
    ('CA', 'Canada', '{"Canada"}', 'Ottawa', '{"Ottawa"}', 'Amériques'),
    ('CL', 'Chili', '{"Chili"}', 'Santiago', '{"Santiago","Santiago du Chili","Santiago de Chile"}', 'Amériques'),
    ('CO', 'Colombie', '{"Colombie"}', 'Bogota', '{"Bogota","Bogotá"}', 'Amériques'),
    ('CR', 'Costa Rica', '{"Costa Rica"}', 'San José', '{"San José"}', 'Amériques'),
    ('CU', 'Cuba', '{"Cuba"}', 'La Havane', '{"La Havane","Havane","La Habana"}', 'Amériques'),
    ('DM', 'Dominique', '{"Dominique"}', 'Roseau', '{"Roseau"}', 'Amériques'),
    ('EC', 'Équateur', '{"Équateur"}', 'Quito', '{"Quito"}', 'Amériques'),
    ('US', 'États-Unis', '{"États-Unis","États-Unis d''Amérique","USA","US"}', 'Washington', '{"Washington","Washington DC","Washington D.C."}', 'Amériques'),
    ('GD', 'Grenade', '{"Grenade"}', 'Saint-Georges', '{"Saint-Georges","Saint Georges","Saint George''s","St George''s"}', 'Amériques'),
    ('GT', 'Guatemala', '{"Guatemala"}', 'Guatemala', '{"Guatemala","Guatemala City","Ciudad de Guatemala","Ville de Guatemala"}', 'Amériques'),
    ('GY', 'Guyana', '{"Guyana","République coopérative du Guyana"}', 'Georgetown', '{"Georgetown"}', 'Amériques'),
    ('HT', 'Haïti', '{"Haïti"}', 'Port-au-Prince', '{"Port-au-Prince"}', 'Amériques'),
    ('HN', 'Honduras', '{"Honduras"}', 'Tegucigalpa', '{"Tegucigalpa"}', 'Amériques'),
    ('JM', 'Jamaïque', '{"Jamaïque"}', 'Kingston', '{"Kingston"}', 'Amériques'),
    ('MX', 'Mexique', '{"Mexique"}', 'Mexico', '{"Mexico","Ciudad de México"}', 'Amériques'),
    ('NI', 'Nicaragua', '{"Nicaragua"}', 'Managua', '{"Managua"}', 'Amériques'),
    ('PA', 'Panama', '{"Panama"}', 'Panama', '{"Panama","Panama City","Ciudad de Panamá"}', 'Amériques'),
    ('PY', 'Paraguay', '{"Paraguay"}', 'Asunción', '{"Asunción","Asuncion","Assomption"}', 'Amériques'),
    ('PE', 'Pérou', '{"Pérou"}', 'Lima', '{"Lima"}', 'Amériques'),
    ('DO', 'République dominicaine', '{"République dominicaine"}', 'Saint-Domingue', '{"Saint-Domingue","Santo Domingo"}', 'Amériques'),
    ('KN', 'Saint-Christophe-et-Niévès', '{"Saint-Christophe-et-Niévès","Saint-Kitts-et-Nevis","Saint-Christophe-et-Nevis"}', 'Basseterre', '{"Basseterre"}', 'Amériques'),
    ('LC', 'Sainte-Lucie', '{"Sainte-Lucie"}', 'Castries', '{"Castries"}', 'Amériques'),
    ('VC', 'Saint-Vincent-et-les-Grenadines', '{"Saint-Vincent-et-les-Grenadines","Saint-Vincent"}', 'Kingstown', '{"Kingstown"}', 'Amériques'),
    ('SV', 'Salvador', '{"Salvador","El Salvador"}', 'San Salvador', '{"San Salvador"}', 'Amériques'),
    ('SR', 'Suriname', '{"Suriname","Surinam"}', 'Paramaribo', '{"Paramaribo"}', 'Amériques'),
    ('TT', 'Trinité-et-Tobago', '{"Trinité-et-Tobago","Trinidad-et-Tobago","Trinité et Tobago"}', 'Port-d''Espagne', '{"Port-d''Espagne","Port d''Espagne","Port of Spain"}', 'Amériques'),
    ('UY', 'Uruguay', '{"Uruguay"}', 'Montevideo', '{"Montevideo"}', 'Amériques'),
    ('VE', 'Venezuela', '{"Venezuela","Vénézuéla"}', 'Caracas', '{"Caracas"}', 'Amériques'),
    ('AF', 'Afghanistan', '{"Afghanistan"}', 'Kaboul', '{"Kaboul","Kabul"}', 'Asie'),
    ('SA', 'Arabie saoudite', '{"Arabie saoudite","Royaume d''Arabie saoudite"}', 'Riyad', '{"Riyad","Riyadh","Ryad"}', 'Asie'),
    ('AM', 'Arménie', '{"Arménie"}', 'Erevan', '{"Erevan","Yerevan"}', 'Asie'),
    ('AZ', 'Azerbaïdjan', '{"Azerbaïdjan"}', 'Bakou', '{"Bakou","Baku"}', 'Asie'),
    ('BH', 'Bahreïn', '{"Bahreïn","Bahrain"}', 'Manama', '{"Manama"}', 'Asie'),
    ('BD', 'Bangladesh', '{"Bangladesh"}', 'Dacca', '{"Dacca","Dhaka"}', 'Asie'),
    ('BT', 'Bhoutan', '{"Bhoutan","Bhutan"}', 'Thimphou', '{"Thimphou","Thimphu","Thimbou"}', 'Asie'),
    ('MM', 'Birmanie', '{"Birmanie","Myanmar"}', 'Naypyidaw', '{"Naypyidaw","Nay Pyi Taw","Naypyitaw"}', 'Asie'),
    ('BN', 'Brunei', '{"Brunei","Brunei Darussalam","Brunéi"}', 'Bandar Seri Begawan', '{"Bandar Seri Begawan"}', 'Asie'),
    ('KH', 'Cambodge', '{"Cambodge"}', 'Phnom Penh', '{"Phnom Penh"}', 'Asie'),
    ('CN', 'Chine', '{"Chine","République populaire de Chine","RPC"}', 'Pékin', '{"Pékin","Beijing"}', 'Asie'),
    ('KP', 'Corée du Nord', '{"Corée du Nord","République populaire démocratique de Corée","RPDC"}', 'Pyongyang', '{"Pyongyang"}', 'Asie'),
    ('KR', 'Corée du Sud', '{"Corée du Sud","République de Corée"}', 'Séoul', '{"Séoul","Seoul"}', 'Asie'),
    ('AE', 'Émirats arabes unis', '{"Émirats arabes unis","EAU","Émirats"}', 'Abou Dabi', '{"Abou Dabi","Abou Dhabi","Abu Dhabi"}', 'Asie'),
    ('GE', 'Géorgie', '{"Géorgie"}', 'Tbilissi', '{"Tbilissi","Tbilisi"}', 'Asie'),
    ('IN', 'Inde', '{"Inde"}', 'New Delhi', '{"New Delhi","Delhi","Nouvelle-Delhi"}', 'Asie'),
    ('ID', 'Indonésie', '{"Indonésie"}', 'Jakarta', '{"Jakarta","Djakarta","Nusantara"}', 'Asie'),
    ('IQ', 'Irak', '{"Irak","Iraq"}', 'Bagdad', '{"Bagdad","Baghdad"}', 'Asie'),
    ('IR', 'Iran', '{"Iran","République islamique d''Iran","Perse"}', 'Téhéran', '{"Téhéran","Tehran"}', 'Asie'),
    ('IL', 'Israël', '{"Israël"}', 'Jérusalem', '{"Jérusalem","Tel Aviv","Tel-Aviv"}', 'Asie'),
    ('JP', 'Japon', '{"Japon"}', 'Tokyo', '{"Tokyo"}', 'Asie'),
    ('JO', 'Jordanie', '{"Jordanie"}', 'Amman', '{"Amman"}', 'Asie'),
    ('KZ', 'Kazakhstan', '{"Kazakhstan"}', 'Astana', '{"Astana","Noursoultan","Nur-Sultan"}', 'Asie'),
    ('KG', 'Kirghizistan', '{"Kirghizistan","Kirghizstan","Kirghizie"}', 'Bichkek', '{"Bichkek","Bishkek"}', 'Asie'),
    ('KW', 'Koweït', '{"Koweït","Kuwait"}', 'Koweït', '{"Koweït","Koweït City","Koweït-ville","Kuwait City"}', 'Asie'),
    ('LA', 'Laos', '{"Laos","République démocratique populaire lao"}', 'Vientiane', '{"Vientiane"}', 'Asie'),
    ('LB', 'Liban', '{"Liban"}', 'Beyrouth', '{"Beyrouth","Beirut"}', 'Asie'),
    ('MY', 'Malaisie', '{"Malaisie"}', 'Kuala Lumpur', '{"Kuala Lumpur","Putrajaya"}', 'Asie'),
    ('MV', 'Maldives', '{"Maldives"}', 'Malé', '{"Malé","Male"}', 'Asie'),
    ('MN', 'Mongolie', '{"Mongolie"}', 'Oulan-Bator', '{"Oulan-Bator","Ulaanbaatar","Oulan Bator"}', 'Asie'),
    ('NP', 'Népal', '{"Népal"}', 'Katmandou', '{"Katmandou","Kathmandou","Kathmandu"}', 'Asie'),
    ('OM', 'Oman', '{"Oman","Sultanat d''Oman"}', 'Mascate', '{"Mascate","Muscat"}', 'Asie'),
    ('UZ', 'Ouzbékistan', '{"Ouzbékistan"}', 'Tachkent', '{"Tachkent","Tashkent"}', 'Asie'),
    ('PK', 'Pakistan', '{"Pakistan"}', 'Islamabad', '{"Islamabad"}', 'Asie'),
    ('PS', 'Palestine', '{"Palestine","État de Palestine","Territoires palestiniens"}', 'Ramallah', '{"Ramallah","Jérusalem-Est","Jérusalem"}', 'Asie'),
    ('PH', 'Philippines', '{"Philippines"}', 'Manille', '{"Manille","Manila"}', 'Asie'),
    ('QA', 'Qatar', '{"Qatar"}', 'Doha', '{"Doha"}', 'Asie'),
    ('SG', 'Singapour', '{"Singapour","Singapore"}', 'Singapour', '{"Singapour","Singapore"}', 'Asie'),
    ('LK', 'Sri Lanka', '{"Sri Lanka","Ceylan"}', 'Sri Jayewardenepura Kotte', '{"Sri Jayewardenepura Kotte","Sri Jayawardenapura Kotte","Kotte","Colombo"}', 'Asie'),
    ('SY', 'Syrie', '{"Syrie","République arabe syrienne"}', 'Damas', '{"Damas","Damascus"}', 'Asie'),
    ('TJ', 'Tadjikistan', '{"Tadjikistan"}', 'Douchanbé', '{"Douchanbé","Dushanbe"}', 'Asie'),
    ('TW', 'Taïwan', '{"Taïwan","République de Chine","Formose"}', 'Taipei', '{"Taipei","Taïpei","Taipeh"}', 'Asie'),
    ('TH', 'Thaïlande', '{"Thaïlande","Siam"}', 'Bangkok', '{"Bangkok"}', 'Asie'),
    ('TL', 'Timor oriental', '{"Timor oriental","Timor-Leste","Timor-Est"}', 'Dili', '{"Dili"}', 'Asie'),
    ('TM', 'Turkménistan', '{"Turkménistan"}', 'Achgabat', '{"Achgabat","Ashgabat","Achkhabad"}', 'Asie'),
    ('TR', 'Turquie', '{"Turquie","Türkiye"}', 'Ankara', '{"Ankara"}', 'Asie'),
    ('VN', 'Vietnam', '{"Vietnam","Viêt Nam","Viet Nam"}', 'Hanoï', '{"Hanoï","Hanoi"}', 'Asie'),
    ('YE', 'Yémen', '{"Yémen"}', 'Sanaa', '{"Sanaa","Sana''a","Aden"}', 'Asie'),
    ('AL', 'Albanie', '{"Albanie","République d''Albanie"}', 'Tirana', '{"Tirana"}', 'Europe'),
    ('DE', 'Allemagne', '{"Allemagne","République fédérale d''Allemagne","RFA"}', 'Berlin', '{"Berlin"}', 'Europe'),
    ('AD', 'Andorre', '{"Andorre","Principauté d''Andorre"}', 'Andorre-la-Vieille', '{"Andorre-la-Vieille","Andorra la Vella"}', 'Europe'),
    ('AT', 'Autriche', '{"Autriche","République d''Autriche"}', 'Vienne', '{"Vienne"}', 'Europe'),
    ('BE', 'Belgique', '{"Belgique","Royaume de Belgique"}', 'Bruxelles', '{"Bruxelles"}', 'Europe'),
    ('BY', 'Biélorussie', '{"Biélorussie","Bélarus","République du Bélarus","République de Biélorussie"}', 'Minsk', '{"Minsk"}', 'Europe'),
    ('BA', 'Bosnie-Herzégovine', '{"Bosnie-Herzégovine","Bosnie","Bosnie et Herzégovine"}', 'Sarajevo', '{"Sarajevo"}', 'Europe'),
    ('BG', 'Bulgarie', '{"Bulgarie","République de Bulgarie"}', 'Sofia', '{"Sofia"}', 'Europe'),
    ('CY', 'Chypre', '{"Chypre","République de Chypre"}', 'Nicosie', '{"Nicosie"}', 'Europe'),
    ('HR', 'Croatie', '{"Croatie","République de Croatie"}', 'Zagreb', '{"Zagreb"}', 'Europe'),
    ('DK', 'Danemark', '{"Danemark","Royaume du Danemark"}', 'Copenhague', '{"Copenhague"}', 'Europe'),
    ('ES', 'Espagne', '{"Espagne","Royaume d''Espagne"}', 'Madrid', '{"Madrid"}', 'Europe'),
    ('EE', 'Estonie', '{"Estonie","République d''Estonie"}', 'Tallinn', '{"Tallinn","Tallin"}', 'Europe'),
    ('FI', 'Finlande', '{"Finlande","République de Finlande"}', 'Helsinki', '{"Helsinki"}', 'Europe'),
    ('FR', 'France', '{"France","République française"}', 'Paris', '{"Paris"}', 'Europe'),
    ('GR', 'Grèce', '{"Grèce","République hellénique"}', 'Athènes', '{"Athènes"}', 'Europe'),
    ('HU', 'Hongrie', '{"Hongrie"}', 'Budapest', '{"Budapest"}', 'Europe'),
    ('IE', 'Irlande', '{"Irlande","République d''Irlande","Éire","Eire"}', 'Dublin', '{"Dublin"}', 'Europe'),
    ('IS', 'Islande', '{"Islande","République d''Islande"}', 'Reykjavik', '{"Reykjavik"}', 'Europe'),
    ('IT', 'Italie', '{"Italie","République italienne"}', 'Rome', '{"Rome"}', 'Europe'),
    ('XK', 'Kosovo', '{"Kosovo","République du Kosovo"}', 'Pristina', '{"Pristina","Prishtina"}', 'Europe'),
    ('LV', 'Lettonie', '{"Lettonie","République de Lettonie"}', 'Riga', '{"Riga"}', 'Europe'),
    ('LI', 'Liechtenstein', '{"Liechtenstein","Principauté du Liechtenstein"}', 'Vaduz', '{"Vaduz"}', 'Europe'),
    ('LT', 'Lituanie', '{"Lituanie","République de Lituanie"}', 'Vilnius', '{"Vilnius"}', 'Europe'),
    ('LU', 'Luxembourg', '{"Luxembourg","Grand-Duché de Luxembourg"}', 'Luxembourg', '{"Luxembourg","Luxembourg-Ville"}', 'Europe'),
    ('MK', 'Macédoine du Nord', '{"Macédoine du Nord","Macédoine","ARYM","Ex-République yougoslave de Macédoine"}', 'Skopje', '{"Skopje"}', 'Europe'),
    ('MT', 'Malte', '{"Malte","République de Malte"}', 'La Valette', '{"La Valette","Valette","Valletta"}', 'Europe'),
    ('MD', 'Moldavie', '{"Moldavie","Moldova","République de Moldavie","République de Moldova"}', 'Chisinau', '{"Chisinau","Kichinev"}', 'Europe'),
    ('MC', 'Monaco', '{"Monaco","Principauté de Monaco"}', 'Monaco', '{"Monaco","Monaco-Ville"}', 'Europe'),
    ('ME', 'Monténégro', '{"Monténégro"}', 'Podgorica', '{"Podgorica"}', 'Europe'),
    ('NO', 'Norvège', '{"Norvège","Royaume de Norvège"}', 'Oslo', '{"Oslo"}', 'Europe'),
    ('NL', 'Pays-Bas', '{"Pays-Bas","Hollande","Royaume des Pays-Bas"}', 'Amsterdam', '{"Amsterdam"}', 'Europe'),
    ('PL', 'Pologne', '{"Pologne","République de Pologne"}', 'Varsovie', '{"Varsovie"}', 'Europe'),
    ('PT', 'Portugal', '{"Portugal","République portugaise"}', 'Lisbonne', '{"Lisbonne"}', 'Europe'),
    ('RO', 'Roumanie', '{"Roumanie"}', 'Bucarest', '{"Bucarest"}', 'Europe'),
    ('GB', 'Royaume-Uni', '{"Royaume-Uni","Grande-Bretagne","UK","Royaume-Uni de Grande-Bretagne et d''Irlande du Nord"}', 'Londres', '{"Londres"}', 'Europe'),
    ('RU', 'Russie', '{"Russie","Fédération de Russie"}', 'Moscou', '{"Moscou"}', 'Europe'),
    ('SM', 'Saint-Marin', '{"Saint-Marin","République de Saint-Marin"}', 'Saint-Marin', '{"Saint-Marin","Ville de Saint-Marin"}', 'Europe'),
    ('RS', 'Serbie', '{"Serbie","République de Serbie"}', 'Belgrade', '{"Belgrade"}', 'Europe'),
    ('SK', 'Slovaquie', '{"Slovaquie","République slovaque"}', 'Bratislava', '{"Bratislava"}', 'Europe'),
    ('SI', 'Slovénie', '{"Slovénie","République de Slovénie"}', 'Ljubljana', '{"Ljubljana"}', 'Europe'),
    ('SE', 'Suède', '{"Suède","Royaume de Suède"}', 'Stockholm', '{"Stockholm"}', 'Europe'),
    ('CH', 'Suisse', '{"Suisse","Confédération suisse","Confédération helvétique"}', 'Berne', '{"Berne"}', 'Europe'),
    ('CZ', 'Tchéquie', '{"Tchéquie","République tchèque"}', 'Prague', '{"Prague"}', 'Europe'),
    ('UA', 'Ukraine', '{"Ukraine"}', 'Kiev', '{"Kiev","Kyiv"}', 'Europe'),
    ('VA', 'Vatican', '{"Vatican","Cité du Vatican","Saint-Siège","État de la Cité du Vatican"}', 'Cité du Vatican', '{"Cité du Vatican","Vatican"}', 'Europe'),
    ('AU', 'Australie', '{"Australie","Commonwealth d''Australie"}', 'Canberra', '{"Canberra"}', 'Océanie'),
    ('FJ', 'Fidji', '{"Fidji","Îles Fidji","Fiji"}', 'Suva', '{"Suva"}', 'Océanie'),
    ('MH', 'Îles Marshall', '{"Îles Marshall","Marshall","République des Îles Marshall"}', 'Majuro', '{"Majuro","Delap-Uliga-Darrit"}', 'Océanie'),
    ('SB', 'Îles Salomon', '{"Îles Salomon","Salomon"}', 'Honiara', '{"Honiara"}', 'Océanie'),
    ('KI', 'Kiribati', '{"Kiribati","Îles Gilbert"}', 'Tarawa', '{"Tarawa","Tarawa-Sud","Bairiki"}', 'Océanie'),
    ('FM', 'Micronésie', '{"Micronésie","États fédérés de Micronésie"}', 'Palikir', '{"Palikir"}', 'Océanie'),
    ('NR', 'Nauru', '{"Nauru","République de Nauru"}', 'Yaren', '{"Yaren"}', 'Océanie'),
    ('NZ', 'Nouvelle-Zélande', '{"Nouvelle-Zélande","Aotearoa"}', 'Wellington', '{"Wellington"}', 'Océanie'),
    ('PW', 'Palaos', '{"Palaos","Palau","Belau","République des Palaos"}', 'Ngerulmud', '{"Ngerulmud","Melekeok","Koror"}', 'Océanie'),
    ('PG', 'Papouasie-Nouvelle-Guinée', '{"Papouasie-Nouvelle-Guinée"}', 'Port Moresby', '{"Port Moresby","Port-Moresby"}', 'Océanie'),
    ('WS', 'Samoa', '{"Samoa","Samoa occidentales","Îles Samoa"}', 'Apia', '{"Apia"}', 'Océanie'),
    ('TO', 'Tonga', '{"Tonga","Îles Tonga","Royaume des Tonga"}', 'Nuku''alofa', '{"Nuku''alofa","Nukualofa"}', 'Océanie'),
    ('TV', 'Tuvalu', '{"Tuvalu","Îles Ellice"}', 'Funafuti', '{"Funafuti","Vaiaku"}', 'Océanie'),
    ('VU', 'Vanuatu', '{"Vanuatu","Nouvelles-Hébrides"}', 'Port-Vila', '{"Port-Vila"}', 'Océanie');

-- Deux cartes par pays (drapeau + capitale), toutes dues immédiatement.
INSERT INTO geo_cards (kind, iso2)
SELECT k.kind, c.iso2 FROM geo_countries c CROSS JOIN (VALUES ('flag'::geo_kind), ('capital'::geo_kind)) AS k(kind);
